name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      with:
        message: |
          A ${{ github.event_name }} event was triggered from
          ${{ repo }} by ${{ repo.namespace }} here at ${{ commit.ref }}
